project:
  type: website

website:
  title: "Emergency Rental Assistance County-level Aggregations"
  navbar:
    left:
      - text: "About"
        href: index.md
      - 1_aggregations.md
      - 2_methods.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    
execute:
  freeze: auto



