project:
  type: website

website:
  title: "Emergency Rental Assistance County-level Aggregations"
  navbar:
    left:
      - href: 0_about.md
      - text: "About"
      - 1_aggregations.md


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



